# Generated by Django 4.0.2 on 2022-02-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('nidNumber', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
