# Generated by Django 4.0.2 on 2022-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_dateofbirth_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Comilla', 'Comilla')], max_length=50),
        ),
    ]
