# Generated by Django 4.0.2 on 2022-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_alter_business_options_alter_businessrooms_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrooms',
            name='business_storage',
        ),
        migrations.RemoveField(
            model_name='room',
            name='personal_storage',
        ),
        migrations.AddField(
            model_name='business',
            name='rooms',
            field=models.ManyToManyField(to='Property.BusinessRooms'),
        ),
        migrations.AddField(
            model_name='personal',
            name='rooms',
            field=models.ManyToManyField(to='Property.Room'),
        ),
    ]
