# Generated by Django 4.0.2 on 2022-02-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_rename_priceperday_business_price_per_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='climatecontrolled',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='name',
            new_name='property_name',
        ),
    ]
