# Generated by Django 4.0.2 on 2022-02-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_rename_name_business_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='climatecontrolled',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='garage',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='personal',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
