# Generated by Django 4.0.2 on 2022-02-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_business_image_climatecontrolled_image_garage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=0, upload_to='')),
                ('description', models.TextField()),
                ('storageID', models.IntegerField(default=-1, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
        migrations.RemoveField(
            model_name='climatecontrolled',
            name='image',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='image',
        ),
    ]
