# Generated by Django 4.0.2 on 2022-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_remove_business_facilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=100)),
                ('facility_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Business Property Facilities',
            },
        ),
        migrations.CreateModel(
            name='ClimateControlledPropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=100)),
                ('facility_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Climate Controlled Property Facilities',
            },
        ),
        migrations.CreateModel(
            name='GaragePropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=100)),
                ('facility_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Garage Property Facilities',
            },
        ),
        migrations.CreateModel(
            name='PersonalPropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=100)),
                ('facility_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Personal Property Facilities',
            },
        ),
        migrations.DeleteModel(
            name='PropertyFacilities',
        ),
    ]
