# Generated by Django 4.0.2 on 2022-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_businesspropertyfacilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facilities',
            field=models.ManyToManyField(to='Property.BusinessPropertyFacilities'),
        ),
        migrations.AddField(
            model_name='climatecontrolled',
            name='facilities',
            field=models.ManyToManyField(to='Property.ClimateControlledPropertyFacilities'),
        ),
        migrations.AddField(
            model_name='garage',
            name='facilities',
            field=models.ManyToManyField(to='Property.GaragePropertyFacilities'),
        ),
        migrations.AddField(
            model_name='personal',
            name='facilities',
            field=models.ManyToManyField(to='Property.PersonalPropertyFacilities'),
        ),
    ]
