# Generated by Django 4.0.2 on 2022-02-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_photo_remove_business_image_and_more'),
        ('Property', '0008_business_facilities_climatecontrolled_facilities_and_more'),
    ]

    operations = [
    ]
