# Generated by Django 4.0.2 on 2022-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0009_merge_20220217_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
