# Generated by Django 4.0.2 on 2022-02-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0010_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='storageID',
            field=models.IntegerField(default=0),
        ),
    ]
