# Generated by Django 4.0.2 on 2022-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0010_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='storageID',
            field=models.IntegerField(default=-1),
        ),
    ]
