# Generated by Django 4.0.2 on 2022-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0011_photo_storageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='storageType',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
