# Generated by Django 4.0.2 on 2022-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0013_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255),
        ),
        migrations.AlterField(
            model_name='climatecontrolled',
            name='location',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255),
        ),
        migrations.AlterField(
            model_name='garage',
            name='location',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255),
        ),
        migrations.AlterField(
            model_name='personal',
            name='location',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=255),
        ),
    ]
