# Generated by Django 4.0.2 on 2022-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0014_alter_business_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location_district',
            field=models.CharField(choices=[('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Comilla', 'Comilla')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='climatecontrolled',
            name='location_district',
            field=models.CharField(choices=[('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Comilla', 'Comilla')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='garage',
            name='location_district',
            field=models.CharField(choices=[('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Comilla', 'Comilla')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='personal',
            name='location_district',
            field=models.CharField(choices=[('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Dinajpur', 'Dinajpur'), ('Comilla', 'Comilla')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='climatecontrolled',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='garage',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
