# Generated by Django 4.0.2 on 2022-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0015_business_location_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='max_vehicle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='max_guest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, to='Property.BusinessPropertyFacilities'),
        ),
        migrations.AlterField(
            model_name='business',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, to='Property.BusinessRooms'),
        ),
        migrations.AlterField(
            model_name='climatecontrolled',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, to='Property.ClimateControlledPropertyFacilities'),
        ),
        migrations.AlterField(
            model_name='climatecontrolled',
            name='machinery',
            field=models.ManyToManyField(blank=True, null=True, to='Property.Machinery'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, to='Property.GaragePropertyFacilities'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='vehicles',
            field=models.ManyToManyField(blank=True, null=True, to='Property.Vehicle'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, to='Property.PersonalPropertyFacilities'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, to='Property.Room'),
        ),
    ]
